services:
  - type: background
    name: solana-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: "7845913453:AAGdE4k2nQy-jVqwpQe6gVydT819Eth-aPA"
      - key: TELEGRAM_CHAT_ID
        value: "5405376313"
      - key: SOLANA_RPC_URL
        value: "https://api.mainnet-beta.solana.com"
